### ISSUE TITLE
How do I remove a vertical line from a button with SVG background?

### ISSUE THREAD

**Issue by uri-rodberg** [speedy-net/speedy-net#29]
We have a button with a background in SVG, and there is a vertical line on the right side with Chrome - but only in the desktop (Chrome version 90.0.4430.93) and not with Firefox. I'm trying to remove the vertical line. How do I remove the vertical line?

The website is https://en.speedymatch.com/, screenshot: [![screenshot][1]][1]

The HTML is:

```html
<div class="form-group"> <div class=""> <input type="submit"
    name="submit"
    value="Create an account"
    
        class="btn btn-primary btn-lg btn-arrow-right"
        id="submit-id-submit"
    
    
    /> </div> </div>
```

CSS is:
```css
.btn-primary.btn-arrow-right,
.btn-primary.btn-arrow-right:not(:disabled):not(.disabled):not(:focus):active,
.btn-primary.btn-arrow-right:not(:disabled):not(.disabled):not(:focus).active {
  background-color: #ff1c32;
  -webkit-mask: url("/static/speedy-match/images/btn-arrow-right.svg") no-repeat;
  border: transparent;
  padding-right: 3em; }
```

And the SVG file does not contain a vertical line.

https://stackoverflow.com/questions/67457568/how-do-i-remove-a-vertical-line-from-a-button-with-svg-background

  [1]: https://i.stack.imgur.com/ASvLw.png
